import './global.css';

import { QueryClientProvider } from '@/components/providers/QueryClient';

export const metadata = {
  title: 'Fullstack Challenge',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
